language: shell
os: linux

env:
  global:
    - IMAGE=registry.gitlab.com/modmyclassic/docker-autodevops-buildenvs/mmc-crosscompiler-docker-image:latest_internal
    - TARGETBUILD=kronos_libretro
  jobs:
    - TARGET=classic_armv7_a7 CLOUD_DIR=NESC
    - TARGET=classic_armv8_a35 CLOUD_DIR=PSC

services:
  - docker

before_script:
  - docker login -u ${GITLAB_USER} -p ${GITLAB_PASS} registry.gitlab.com
  - docker pull ${IMAGE}
  - docker run -it -d --name crosscomp ${IMAGE} bash
  - docker exec -it --privileged crosscomp bash -c "git clone --depth=50 --branch=kronos --recursive https://github.com/${TRAVIS_REPO_SLUG} ${TRAVIS_REPO_SLUG}"
script:
  - docker exec -it --privileged crosscomp bash -c "cd ${TRAVIS_REPO_SLUG} && make CC=arm-linux-gnueabihf-gcc-6 CXX=arm-linux-gnueabihf-g++-6 AS=arm-linux-gnueabihf-gcc-6 CC_AS=arm-linux-gnueabihf-gcc-6 AR=arm-linux-gnueabihf-gcc-ar-6 platform=${TARGET} -C yabause/src/libretro -j -f Makefile clean"
  - docker exec -it --privileged crosscomp bash -c "cd ${TRAVIS_REPO_SLUG} && make CC=arm-linux-gnueabihf-gcc-6 CXX=arm-linux-gnueabihf-g++-6 AS=arm-linux-gnueabihf-gcc-6 CC_AS=arm-linux-gnueabihf-gcc-6 AR=arm-linux-gnueabihf-gcc-ar-6 platform=${TARGET} -C yabause/src/libretro -j -f Makefile"
  - docker exec -it --privileged crosscomp bash -c "chown 600 ~/.keys/release_private_key.pem"
  - docker exec -it --privileged crosscomp bash -c "find ${TRAVIS_REPO_SLUG} -name '*.so' -print -exec xz '{}' \; -exec mv '{}'.xz '{}' \;"
  - docker exec -it --privileged crosscomp bash -c "cd ${TRAVIS_REPO_SLUG} && echo -e  'cd /var/www/html/cores/Automated_Builds/${CLOUD_DIR}\nput ${TARGETBUILD}.so' | sftp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ~/.keys/release_private_key.pem docker@classicmodscloud.com"
